### ISSUE TITLE
i3 to-do

### ISSUE THREAD

**Issue by Kevin-Mok** [Kevin-Mok/linux-config#33]
- [x] split this up into multiple issues with label
- [ ] [pywal color scheme](https://github.com/dylanaraps/pywal)
- [ ] [i3-gaps](https://github.com/Airblader/i3)
- [ ] custom status bar separator
- [ ] start windows in custom workspace on launch
- [ ] open terminal from last location
- [ ] rotate monitors keybinding (or toggle like #23)

**Comment by Kevin-Mok** [comment]
- [X] Setup workspace icons for i3

**Comment by Kevin-Mok** [comment]
Split each issue in comment with i3 label.
